SELECT 
    CASE economico_tipo_trabalho
        WHEN '01' THEN 'Empregado doméstico, diarista, cozinheiro (em domicílios particulares)'
        WHEN '02' THEN 'Faxineiro, auxiliar de limpeza (empresa pública ou privada)'
        WHEN '03' THEN 'Auxiliar de escritório, escriturário'
        WHEN '04' THEN 'Secretária, recepcionista'
        WHEN '05' THEN 'Operador de Telemarketing'
        WHEN '06' THEN 'Comerciante (dono do bar, da loja etc.)'
        WHEN '07' THEN 'Balconista, vendedor de loja'
        WHEN '08' THEN 'Vendedor a domicílio, representante de vendas, vendedor de catálogo (Avon, Natura etc.)'
        WHEN '09' THEN 'Vendedor ambulante (feirante, camelô, comerciante de rua, quiosque)'
        WHEN '10' THEN 'Cozinheiro e garçom (de restaurantes, empresas)'
        WHEN '11' THEN 'Padeiro, açougueiro e doceiro'
        WHEN '12' THEN 'Agricultor, criador de animais, pescador, silvicultor e jardineiro'
        WHEN '13' THEN 'Auxiliar da agropecuária (colhedor de frutas, boia fria, etc.)'
        WHEN '14' THEN 'Motorista (de aplicativo, de taxi, de van, de mototáxi, de ônibus)'
        WHEN '15' THEN 'Motorista de caminhão (caminhoneiro)'
        WHEN '16' THEN 'Motoboy'
        WHEN '17' THEN 'Entregador de mercadorias (de restaurante, farmácia, loja, Uber Eats, IFood, Rappy etc.)'
        WHEN '18' THEN 'Pedreiro, servente de pedreiro, pintor, eletricista, marceneiro'
        WHEN '19' THEN 'Mecânico de veículos, máquinas industriais etc.'
        WHEN '20' THEN 'Artesão, costureiro e sapateiro'
        WHEN '21' THEN 'Cabeleireiro, manicure e afins'
        WHEN '22' THEN 'Operador de máquinas, montador na indústria'
        WHEN '23' THEN 'Auxiliar de produção, de carga e descarga'
        WHEN '24' THEN 'Professor da educação infantil, ensino fundamental, médio ou superior'
        WHEN '25' THEN 'Pedagogo, professor de idiomas, música, arte e reforço escolar'
        WHEN '26' THEN 'Médico, enfermeiro, profissionais de saúde de nível superior'
        WHEN '27' THEN 'Técnico, profissional da saúde de nível médio'
        WHEN '28' THEN 'Cuidador de crianças, doentes ou idosos'
        WHEN '29' THEN 'Segurança, vigilante, trabalhador dos serviços de proteção'
        WHEN '30' THEN 'Policial civil'
        WHEN '31' THEN 'Porteiro, zelador'
        WHEN '32' THEN 'Artista, religioso (padre, pastor etc.)'
        WHEN '33' THEN 'Diretor, gerente, cargo político ou comissionado'
        WHEN '34' THEN 'Outra profissão de nível superior (advogado, engenheiro, contador, jornalista etc.)'
        WHEN '35' THEN 'Outro técnico ou profissional de nível médio'
        WHEN '36' THEN 'Outros'
        ELSE 'Não especificado'
    END AS descricao_trabalho,
    COUNT(*) AS total
FROM economico
GROUP BY economico_tipo_trabalho
ORDER BY economico_tipo_trabalho;
